# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wssh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='菜单名')),
                ('show', models.BooleanField(default=False, help_text='菜单是否显示，默认不显示', verbose_name='是否显示')),
                ('url', models.CharField(blank=True, default='javascript:void(0)', max_length=300, null=True, verbose_name='菜单url')),
                ('priority', models.IntegerField(blank=True, default=-1, help_text='菜单显示顺序，优先级越大显示越靠前', null=True, verbose_name='显示优先级')),
                ('permission_id', models.IntegerField(error_messages={'field-permission_id': '只能输入数字'}, help_text='给菜单设置一个编码，用于权限控制', verbose_name='权限编码')),
                ('parent', models.ForeignKey(blank=True, default='0', help_text='如果添加的是子菜单，请选择父菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='wssh.Menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
